name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: r-ex
          token: ${{secrets.PERSONAL_TOKEN}}
          base: main
          head: main
          merge_method: merge
          auto_approve: true
          auto_merge: true