name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          personal_token: ${{secrets.PERSONAL_TOKEN}}
          owner: r-ex
          base: main
          head: main
          auto_approve: true

  nightly-trigger:
    needs: sync
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Nightly
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.PERSONAL_TOKEN}}
          repository: biast12/LegionPlus
          event-type: Autosync-DONE
          ref: main