name: Upload Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nightly:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 1

    - name: Check for commits within the last 24 hours
      uses: AlexHolderDeveloper/CommitsWithinTime@v1.1.5
      id: commitswithintime
      with:
        hours: 24

    - name: Setup MSBuild
      if: steps.commitswithintime.outputs.has-new-commits-within-time != 'false'
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Get short commit SHA
      if: steps.commitswithintime.outputs.has-new-commits-within-time != 'false'
      run: echo SHA7=$(git rev-parse --short HEAD) >> $env:GITHUB_ENV

    - name: Build Legion+
      if: steps.commitswithintime.outputs.has-new-commits-within-time != 'false'
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m . /p:Configuration=Release

    - name: ZIP Executable
      if: steps.commitswithintime.outputs.has-new-commits-within-time != 'false'
      uses: vimtor/action-zip@v1
      with:
        files: bin/x64/Release/LegionPlus.exe
        dest: LegionPlus.zip

    - name: Upload Release Build
      if: steps.commitswithintime.outputs.has-new-commits-within-time != 'false'
      uses: WebFreak001/deploy-nightly@v1.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        upload_url: https://uploads.github.com/repos/biast12/LegionPlus/releases/131409444/assets{?name,label}
        release_id: 102559614
        asset_path: LegionPlus.zip
        asset_name: LegionPlus.zip
        asset_content_type: application/zip
        max_releases: 1

    - name: Update Release
      if: steps.commitswithintime.outputs.has-new-commits-within-time != 'false'
      uses: richardsimko/update-tag@v1.0.5
      with:
        tag_name: 'Release'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
